### ISSUE TITLE
errors js-controller 3.0.x :-)

### ISSUE THREAD

**Issue by Ilovegym66** [Omega236/ioBroker.timecounter#6]
Hi, gerade hier mal getestet, es kommt das:

`

timecounter.1 | 2020-04-13 11:57:24.832 | info | (9641) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
timecounter.1 | 2020-04-13 11:57:24.832 | info | (9641) terminating
timecounter.1 | 2020-04-13 11:57:24.828 | info | (9641) cleaned everything up...
timecounter.1 | 2020-04-13 11:57:24.828 | error | at async Timecounter.onStateChange (/opt/iobroker/node_modules/iobroker.timecounter/main.js:65:7)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at Timecounter.calcNewTimeinCounter (/opt/iobroker/node_modules/iobroker.timecounter/main.js:158:18)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at Timecounter.setForeignStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1566:16)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at new Promise (<anonymous>)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1567:16
timecounter.1 | 2020-04-13 11:57:24.828 | error | at Timecounter.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5941:21)
timecounter.1 | 2020-04-13 11:57:24.828 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1570:39
timecounter.1 | 2020-04-13 11:57:24.828 | error | (9641) Error: undefined is not a valid state value
timecounter.1 | 2020-04-13 11:57:24.826 | error | (9641) uncaught exception: undefined is not a valid state value
timecounter.1 | 2020-04-13 11:57:24.826 | warn | (9641) This value will not be set in future versions. Please report this to the developer.
timecounter.1 | 2020-04-13 11:57:24.825 | warn | (9641) State value to set is invalid for javascript.0.system.timeCounter: The state is missing the required property val!
timecounter.1 | 2020-04-13 11:57:24.823 | info | (9641) javascript.0.system.AnwesendBernd state changed
timecounter.1 | 2020-04-13 11:57:05.967 | info | (9641) javascript.0.system.AnwesendBernd state changed
timecounter.1 | 2020-04-13 11:56:34.647 | info | (9641) initial completed
timecounter.1 | 2020-04-13 11:56:34.554 | info | (9641) initial (check OK): javascript.0.system.AnwesendBernd
timecounter.1 | 2020-04-13 11:56:33.089 | info | (9641) inital all Objects
readFile | 2020-04-13 11:56:23.922 | warn | will not read this file (words.js) in future versions: template.admin is not an object of type "meta"
timecounter.1 | 2020-04-13 11:55:38.886 | info | (9641) initial completed
timecounter.1 | 2020-04-13 11:55:36.436 | info | (9641) inital all Objects
timecounter.1 | 2020-04-13 11:55:36.421 | info | (9641) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.timecounter, node: v12.16.1, js-controller: 3.0.7
host.ioB-D10 | 2020-04-13 11:55:34.614 | info | instance system.adapter.timecounter.1 started with pid 9641

`

**Comment by Ilovegym66** [comment]
push :-)
